---
stages:
- name: BUILD
  inputs:
  - type: git
    branch: master
    url: ${GIT_REPO_URL}
    token: ${GIT_REPO_TOKEN}	
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
- name: DEV
  inputs:
  - type: job
    stage: BUILD
    job: Build
  triggers:
  - type: stage
  properties:
  - name: CF_APP_NAME
    value: undefined
    type: text
  - name: APP_URL
    value: undefined
    type: text
  jobs:
  - name: Deploy to dev
    type: deployer
    target:
      region_id: ${DEV_REGION_NAME}
      organization_guid: ${DEV_ORG_NAME}
      space_guid: ${CF_SPACE_ID}
      application: ${CF_APP_NAME}
    script: |-
      #!/bin/bash
      cf create-service cloudantNoSQLDB Shared myMicroservicesCloudant
      # Publish catalogAPI
      if ! cf service catalogAPI > /dev/null; then
      cf cups catalogAPI
      fi
      # Push app
      export CF_APP_NAME="$CF_APP-dev"
      cf push "${CF_APP_NAME}"
      # Update catalogAPI
      HOST=http://$(cf app $CF_APP_NAME | grep urls: | awk '{print $2}')
      cf uups catalogAPI -p '{"host":"'$HOST'"}'
      # View logs
      #cf logs "${CF_APP_NAME}" --recent
- name: QA
  inputs:
  - type: job
    stage: BUILD
    job: Build
  triggers:
  - type: stage
  properties:
  - name: CF_APP_NAME
    value: undefined
    type: text
  - name: APP_URL
    value: undefined
    type: text
  jobs:
  - name: Deploy to QA
    type: deployer
    target:
      region_id: ${QA_REGION_NAME}
      organization_guid: ${DEV_ORG_NAME}
      space_guid: ${CF_SPACE_ID}
      application: ${CF_APP_NAME}
    script: |-
      #!/bin/bash
      cf create-service cloudantNoSQLDB Shared myMicroservicesCloudant
      # Publish catalogAPI
      if ! cf service catalogAPI > /dev/null; then
      cf cups catalogAPI
      fi
      # Push app
      export CF_APP_NAME="$CF_APP-qa"
      cf push "${CF_APP_NAME}"
      # Update catalogAPI
      HOST=http://$(cf app $CF_APP_NAME | grep urls: | awk '{print $2}')
      cf uups catalogAPI -p '{"host":"'$HOST'"}'
      # View logs
      #cf logs "${CF_APP_NAME}" --recent
- name: PROD
  inputs:
  - type: job
    stage: BUILD
    job: Build
  triggers:
  - type: stage
  properties:
  - name: CF_APP_NAME
    value: undefined
    type: text
  - name: APP_URL
    value: undefined
    type: text
  jobs:
  - name: Deploy to prod
    type: deployer
    target:
      region_id: ${PROD_REGION_NAME}
      organization_guid: ${DEV_ORG_NAME}
      space_guid: ${CF_SPACE_ID}
      application: ${CF_APP_NAME}
    script: |-
      #!/bin/bash
      cf create-service cloudantNoSQLDB Shared myMicroservicesCloudant
      # Publish catalogAPI
      if ! cf service catalogAPI > /dev/null; then
      cf cups catalogAPI
      fi
      # Push app
      export CF_APP_NAME="$CF_APP"
      cf push "${CF_APP_NAME}"
      # Update catalogAPI
      HOST=http://$(cf app $CF_APP_NAME | grep urls: | awk '{print $2}')
      cf uups catalogAPI -p '{"host":"'$HOST'"}'
      # View logs
      #cf logs "${CF_APP_NAME}" --recent

