---
stages:
- name: BUILD
  inputs:
  - type: git
    branch: master
    url: ${GIT_REPO_URL}
    token: ${GIT_REPO_TOKEN}	
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
- name: DEV
  inputs:
  - type: job
    stage: BUILD
    job: Build
  triggers:
  - type: stage
  properties:
  - name: CF_APP_NAME
    value: undefined
    type: text
  - name: APP_URL
    value: undefined
    type: text
  jobs:
  - name: Deploy to dev
    type: deployer
    target:
      region_id: ${DEV_REGION_ID}
      organization: ${DEV_ORG_NAME}
      space: ${DEV_SPACE_NAME}
      application: ${CF_APP_NAME}
    script: |-
      #!/bin/bash
      cf create-service cloudantNoSQLDB Shared myMicroservicesCloudant
      # Publish catalogAPI
      if ! cf service catalogAPI > /dev/null; then
      cf cups catalogAPI
      fi
      # Push app
      export CF_APP_NAME="$CF_APP-dev"
      cf push "${CF_APP_NAME}"
      # Update catalogAPI
      HOST=http://$(cf app $CF_APP_NAME | grep urls: | awk '{print $2}')
      cf uups catalogAPI -p '{"host":"'$HOST'"}'
      # View logs
      #cf logs "${CF_APP_NAME}" --recent
- name: TEST
  inputs:
  - type: job
    stage: BUILD
    job: Build
  triggers:
  - type: stage
  properties:
  - name: CF_APP_NAME
    value: undefined
    type: text
  - name: APP_URL
    value: undefined
    type: text
  jobs:
  - name: Deploy to test
    type: deployer
    target:
      region_id: ${QA_REGION_ID}
      organization: ${DEV_ORG_NAME}
      space: ${DEV_SPACE_NAME}
      application: ${CF_APP_NAME}
    script: |-
      #!/bin/bash
      cf create-service cloudantNoSQLDB Shared myMicroservicesCloudant
      # Publish catalogAPI
      if ! cf service catalogAPI > /dev/null; then
      cf cups catalogAPI
      fi
      # Push app
      export CF_APP_NAME="$CF_APP-qa"
      cf push "${CF_APP_NAME}"
      # Update catalogAPI
      HOST=http://$(cf app $CF_APP_NAME | grep urls: | awk '{print $2}')
      cf uups catalogAPI -p '{"host":"'$HOST'"}'
      # View logs
      #cf logs "${CF_APP_NAME}" --recent
- name: PROD
  inputs:
  - type: job
    stage: BUILD
    job: Build
  triggers:
  - type: stage
  properties:
  - name: CF_APP_NAME
    value: undefined
    type: text
  - name: APP_URL
    value: undefined
    type: text
  - name: ROUTE_DOMAIN
    value: stage1.mybluemix.net
    type: text
  - name: GROUP_SIZE
    value: '3'
    type: text
  - name: TARGET_PLATFORM
    value: CloudFoundry
    type: text
  - name: TEST_RESULT_FOR_AD
    value: ''
    type: text	
  jobs:
  - name: Deploy Single Instance
    type: deployer
    target:
      region_id: ${PROD_REGION_ID}
      organization: ${PROD_ORG_NAME}
      space: ${PROD_SPACE_NAME}
      application: ${CF_APP_NAME}
    script: |-
      #!/bin/bash
      cf create-service cloudantNoSQLDB Shared myMicroservicesCloudant
      # Publish catalogAPI
      if ! cf service catalogAPI > /dev/null; then
      cf cups catalogAPI
      fi
      CF_APP_NAME="${CF_APP}_${BUILD_NUMBER}"
      cf push "${CF_APP_NAME}" --no-route -i 1
      export CF_APP_NAME
  - name: Begin AD
    type: deployer
    extension_id: ibm.devops.services.pipeline.devops.ad_start
    target:
      region_id: ${PROD_REGION_ID}
      organization: ${PROD_ORG_NAME}
      space: ${PROD_SPACE_NAME}
      application: ${CF_APP_NAME}
    RAMPDOWN_DURATION: 1m
    RAMPUP_DURATION: 1m
    COMMAND: |-
      #!/bin/bash
      source ${EXT_DIR}/git_util.sh
      git_retry clone https://github.com/Osthanes/update_service.git activedeploy
      activedeploy/activedeploy_step_1.sh
      # Update catalogAPI
      HOST=http://$(cf app $CF_APP_NAME | grep urls: | awk '{print $2}')
      cf uups catalogAPI -p '{"host":"'$HOST'"}'
  - name: Complete AD
    type: deployer
    extension_id: ibm.devops.services.pipeline.devops.ad_finish
    target:
      region_id: ${PROD_REGION_ID}
      organization: ${PROD_ORG_NAME}
      space: ${PROD_SPACE_NAME}
      application: ${CF_APP_NAME}
    COMMAND: |-
      #!/bin/bash
      source ${EXT_DIR}/git_util.sh
      git_retry clone https://github.com/Osthanes/update_service.git activedeploy
      activedeploy/activedeploy_step_2.sh
