---
stages:
- name: Build Stage
  inputs:
  - type: git
    branch: master
    url: ${GIT_REPO_URL}
    token: ${GIT_REPO_TOKEN}
  triggers:
  - type: commit
  jobs:
  - artifact_dir: output
    name: Build
    type: builder
    build_type: ant
    script: |-
      #!/bin/bash
      ant
- name: Deploy Stage
  inputs:
  - type: job
    stage: Build Stage
    job: Build
  triggers:
  - type: stage
  properties:
  - name: CF_APP_NAME
    value: 'undefined'
    type: text
  - name: APP_URL
    value: 'undefined'
    type: text
  jobs:
  - name: Deploy to dev
    type: deployer
    target:
      url: ${CF_TARGET_URL}
      organization: ${CF_ORGANIZATION}
      space: ${CF_SPACE}
      application: ${CF_APP}
    script: |-
      #!/bin/bash
      cf create-service sqldb sqldb_free myMicroservicesSQL
      cf create-service mqlight standard mqLightService
      # Publish ordersAPI
      if ! cf service ordersAPI > /dev/null; then
      cf cups ordersAPI
      fi
      # Push app
      cf push "${CF_APP}"
      export CF_APP_NAME="$CF_APP"
      # Update ordersAPI
      export HOST=http://$(cf app $CF_APP | grep urls: | awk '{print $2}')
      cf uups ordersAPI -p '{"host":"$\{HOST\}"}'
      # View logs
      #cf logs "${CF_APP}" --recent
